### PR TITLE
Feature fix color theme & UI style

### LINKED ISSUE #218: Capture 頁面字型太大，參考 Google Photo

### LINKED ISSUE #219: PostCapture 字型頁面亦同

### LINKED ISSUE #228: Update UI & color theme
Update UI & color theme

### LINKED ISSUE #235: 仿照 Instagram 的顯示方式，裁切照片以適當 size 顯示
仿照 Instagram 的顯示方式，裁切照片以適當 size 顯示 (方、長；寬三個比例) - (但是我們的原始照片不更動，只在顯示上調整)

### PR DESCRIPTION
**Pull request by CS6**
fix #228  Update UI & color theme (toolbar,text,color,icon, border)
fix #218   Capture 頁面字型太大，參考 Google Photo
fix #219  PostCapture 字型頁面亦同 
fix #235  仿照 Instagram 的顯示方式，裁切照片以適當 size 顯示 
（overflow:hidden;  4:5 , 16:9 , 1:1）

### CODE REVIEW

File: src/app/shared/post-capture-card/post-capture-card.component.ts [hunk 1]
```diff
@@ -11,14 +10,17 @@ export class PostCaptureCardComponent implements OnInit {
...
   longitude!: string;
-
   openMore = false;
 
   ngOnInit() {
     this.latitude = this.asset.information.information.find(info => info.name === 'Current GPS Latitude')?.value || 'unknown';
     this.longitude = this.asset.information.information.find(info => info.name === 'Current GPS Longitude')?.value || 'unknown';
   }
+
+
```
Comment (seanwu1105) [inline src/app/shared/post-capture-card/post-capture-card.component.ts:25]: Unnecessary blank lines.

File: src/theme/variables.scss [hunk 2]
```diff
@@ -8,6 +8,41 @@
 // Be sure that you only ever include this mixin once!
 @include mat-core();
 
+.mat-toolbar {
+  background: #564DFC !important;
```
Comment (seanwu1105) [inline src/theme/variables.scss:12]: Avoid `!important` exception. I think we should use a common CSS class to set the background and color. Though this will result in duplicate code on HTML, bug it makes sure we won't need to override the rule with `!important` again when we have to. E.g. we need to change the background and color for a specific `mat-toolbar` on a specific page.

File: src/app/shared/post-capture-card/post-capture-card.component.ts [hunk 3]
```diff
@@ -11,14 +10,17 @@ export class PostCaptureCardComponent implements OnInit {
 
   @Input() transaction!: Transaction;
   @Input() asset!: Asset;
+  @ViewChild('myIdentifier')
```
Comment (seanwu1105) [inline src/app/shared/post-capture-card/post-capture-card.component.ts:13]: Use a meaningful name instead of `myIdentifier`.

**Review by seanwu1105 — CHANGES_REQUESTED** [review]
See the comments in different files. Also, you have to follow the format rules from Codacy before requesting a re-review.

File: src/app/shared/post-capture-card/post-capture-card.component.scss [hunk 4]
```diff
@@ -7,21 +7,21 @@
...
-  padding-right: 0px;
-  padding-left: 0px;
-  width: 100%;    
+mat-card {
+  padding-right: 0;
+  padding-left: 0;
+  width: 100%;
 }
 
 mat-card .instagram {
```
Comment (seanwu1105) [inline src/app/shared/post-capture-card/post-capture-card.component.scss:19]: The class name `instagram` is not clear for its purpose. Rename it with a meaningful word, such as `fixed-ratio`.

Comment (CS6) [reply src/app/shared/post-capture-card/post-capture-card.component.scss]: 👍

**Comment by CS6** [comment]
@seanwu1105  有空時請幫我 Merge 🙏 感謝大大

File: src/app/shared/post-capture-card/post-capture-card.component.ts [hunk 5]
```diff
@@ -11,10 +10,11 @@ export class PostCaptureCardComponent implements OnInit {
 
   @Input() transaction!: Transaction;
   @Input() asset!: Asset;
+  @ViewChild('igIMG')
```
Comment (seanwu1105) [inline src/app/shared/post-capture-card/post-capture-card.component.ts:13]: `igIMG` is a bad naming. First, it consists of two __abbreviation__: `ig` and `IMG`. This will greatly decrease the readability. Second, it should follow camelCase.

File: src/app/shared/post-capture-card/post-capture-card.component.scss [hunk 6]
```diff
@@ -6,12 +6,50 @@
...
 }
 
 mat-card-content {
   margin-bottom: 0;
+  padding-right: 16px;
+  padding-left: 0;
+}
+
+mat-card-title {
+  font-size: 16px !important;
```
Comment (seanwu1105) [inline src/app/shared/post-capture-card/post-capture-card.component.scss:50]: Avoid using `!important` by applying higher specificity to this CSS rule.

**Review by seanwu1105 — CHANGES_REQUESTED** [review]
Still need to fix some naming and CSS conventions.

**Review by seanwu1105 — APPROVED** [review]
